<script setup lang="ts">
import { reactive, watch } from "vue";
export interface AppSettings { theme: "system" | "dark" | "light"; clientUpdateFrequency: "launch" | "daily" | "weekly" | "monthly" | "never"; contentAutoUpdate: boolean }
export interface RuntimeInfo { platform: string; portable: boolean; appVersion: string; databaseVersion: number; dataRoot: string }
export interface BackupRecord { id: string; backupType: string; fileName: string; sizeBytes: number; createdAt: string; status: string }
const props = defineProps<{ settings: AppSettings; runtime: RuntimeInfo | null; backups: BackupRecord[]; updateStatus: string; updateUrl: string; busy: boolean }>();
const emit = defineEmits<{ saveSettings: [settings: AppSettings]; createBackup: []; restoreBackup: []; exportBackup: [id: string]; importLegacy: []; checkUpdates: []; openUpdatePage: []; openDataFolder: []; exportDiagnostics: [] }>();
const draft = reactive<AppSettings>({ ...props.settings });
watch(() => props.settings, (value) => Object.assign(draft, value), { deep: true });
watch(draft, () => emit("saveSettings", { ...draft }), { deep: true });
function formatBytes(value: number) { return value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`; }
</script>
<template><section class="module-workspace settings-workspace"><header class="page-header"><h2>设置与数据</h2><button type="button" class="secondary-button" @click="emit('openDataFolder')">打开数据目录</button></header><section class="settings-grid"><article class="settings-card"><header><h3>外观</h3></header><label>主题<select v-model="draft.theme"><option value="system">跟随系统</option><option value="dark">深色</option><option value="light">浅色</option></select></label></article><article class="settings-card"><header><h3>更新</h3></header><label>客户端检查频率<select v-model="draft.clientUpdateFrequency"><option value="launch">每次打开</option><option value="daily">每天</option><option value="weekly">每周（默认）</option><option value="monthly">每月</option><option value="never">从不自动检查</option></select></label><div class="button-row"><button type="button" class="secondary-button" :disabled="busy" @click="emit('checkUpdates')">立即检查客户端版本</button><button v-if="updateUrl" type="button" class="primary-button" @click="emit('openUpdatePage')">前往 GitHub 下载</button></div><p v-if="updateStatus" class="setting-status">{{ updateStatus }}</p></article><article class="settings-card wide-card"><header><h3>备份与恢复</h3><p>默认保留 7 个日常、4 个周备份和 3 个升级备份。</p></header><div class="button-row"><button type="button" class="primary-button" :disabled="busy" @click="emit('createBackup')">立即备份</button><button type="button" class="secondary-button" :disabled="busy" @click="emit('restoreBackup')">从备份恢复</button><button type="button" class="secondary-button" :disabled="busy" @click="emit('importLegacy')">导入旧版 ZIP / xy.dat</button></div><div class="backup-list"><article v-for="backup in backups" :key="backup.id"><div><strong>{{ backup.fileName }}</strong><small>{{ backup.backupType }} · {{ new Date(backup.createdAt).toLocaleString('zh-CN') }} · {{ formatBytes(backup.sizeBytes) }}</small></div><span :class="backup.status">{{ backup.status==='available'?'可用':backup.status }}</span><button type="button" @click="emit('exportBackup',backup.id)">导出副本</button></article><p v-if="!backups.length">还没有备份记录</p></div></article><article class="settings-card wide-card"><header><h3>运行与诊断</h3><p>程序不会自动上传报告。需要求助时可手动导出脱敏诊断文本。</p></header><dl class="runtime-list"><div><dt>版本</dt><dd>{{ runtime?.appVersion ?? '—' }}</dd></div><div><dt>数据库</dt><dd>v{{ runtime?.databaseVersion ?? '—' }}</dd></div><div><dt>运行方式</dt><dd>{{ runtime?.portable ? '便携版' : '安装版 / 开发版' }}</dd></div><div><dt>数据目录</dt><dd>{{ runtime?.dataRoot ?? '—' }}</dd></div></dl><button type="button" class="secondary-button" @click="emit('exportDiagnostics')">导出诊断报告</button></article></section></section></template>
