<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
type Dataset = "market"|"nano"|"cookbook"|"activities"|"news";
const data=ref<any>(null),dataset=ref<Dataset>("market"),query=ref(""),selected=ref<any>(null),status=ref(""),busy=ref(false),contentVersion=ref("2026.07.17.1"),newsEnabled=ref(false);
const release=reactive({repository:"chincika/lifeafter-growth-assistant",branch:"main",contentVersion:"2026.07.17.1",latestVersion:"0.1.1",minimumClientVersion:"0.1.0",minimumSupportedVersion:"0.1.0",updateLevel:"optional",updateMessage:"公共资料更新",graceDays:7,includeNews:false,token:""});
const datasetLabels:{id:Dataset;name:string}[]=[{id:"market",name:"物品与配方"},{id:"nano",name:"纳米"},{id:"cookbook",name:"食谱"},{id:"activities",name:"活动"},{id:"news",name:"幸存者快报"}];
const records=computed(()=>{const values=dataset.value==="market"?data.value?.marketItems:dataset.value==="nano"?data.value?.nanoItems:dataset.value==="cookbook"?data.value?.cookbookRecipes:dataset.value==="activities"?data.value?.activities:data.value?.newsEntries;const keyword=query.value.trim().toLowerCase();return(values??[]).filter((item:any)=>!keyword||`${item.name??item.title??""} ${item.method??item.version??""}`.toLowerCase().includes(keyword));});
function label(item:any){return item.name??item.title??item.itemId??item.id}function sublabel(item:any){return dataset.value==="market"?`${item.categoryName} · Lv ${item.level}`:dataset.value==="nano"?`I ${item.nano1.average} · II ${item.nano2.average} · III ${item.nano3.average}`:dataset.value==="cookbook"?item.method:dataset.value==="activities"?`${item.categoryName} · ${item.startDate}`:item.publishedDate;}
function nanoExists(id:string){return records.value.some((item:any)=>item.itemId===id)}
async function load(directory?:string){busy.value=true;try{data.value=await window.maintainerApi.load(directory);contentVersion.value=data.value.contentVersion;release.contentVersion=data.value.contentVersion;newsEnabled.value=data.value.newsEnabled;selected.value=null;status.value="资料校验通过"}catch(error){status.value=String(error)}finally{busy.value=false}}
async function choose(){const directory=await window.maintainerApi.chooseDirectory();if(directory)await load(directory)}
function select(item:any){selected.value=JSON.parse(JSON.stringify(item))}
function add(){if(dataset.value==="market")selected.value={name:"",legacyType:5,level:1,couponCost:0,recipeText:""};else if(dataset.value==="nano")selected.value={itemId:data.value.marketOptions[0]?.id,nano1:{min:0,average:0,max:0},nano2:{min:0,average:0,max:0},nano3:{min:0,average:0,max:0}};else if(dataset.value==="cookbook")selected.value={name:"",method:"",effect:"",duration:"",defaultUnlocked:false};else if(dataset.value==="activities")selected.value={category:data.value.activityCategories[0]?.id,title:"",version:"",condition:"",floors:null,startDate:"",endDate:""};else selected.value={title:"",publishedDate:new Date().toLocaleDateString("sv-SE"),imageUrl:"",imageFile:""};}
async function chooseNewsImage(){if(!selected.value)return;const image=await window.maintainerApi.chooseNewsImage();if(!image)return;selected.value.imageFile=image.imageFile;selected.value.imageUrl="";status.value=`已选择长图：${image.width}×${image.height} · ${(image.sizeBytes/1024/1024).toFixed(1)} MiB`;}
async function save(){if(!selected.value)return;busy.value=true;try{const record=JSON.parse(JSON.stringify(selected.value));data.value=await window.maintainerApi.saveRecord({dataset:dataset.value,record,contentVersion:contentVersion.value,newsEnabled:newsEnabled.value});selected.value=null;release.contentVersion=contentVersion.value;status.value="已校验并保存；原文件旁已生成 .bak 保护副本"}catch(error){status.value=String(error)}finally{busy.value=false}}
async function remove(){if(!selected.value?.id&&!selected.value?.itemId)return;if(!confirm(`确定删除“${label(selected.value)}”？`))return;busy.value=true;try{data.value=await window.maintainerApi.deleteRecord({dataset:dataset.value,id:selected.value.id??selected.value.itemId});selected.value=null;status.value="已删除并重新校验资料"}catch(error){status.value=String(error)}finally{busy.value=false}}
async function build(){busy.value=true;try{const result=await window.maintainerApi.buildRelease({...release});if(!result.canceled)status.value=`发布包已生成：${result.directory}`}catch(error){status.value=String(error)}finally{busy.value=false}}
async function publish(){if(!confirm(`将直接写入 GitHub 仓库 ${release.repository} 的 ${release.branch} 分支，确定继续？`))return;busy.value=true;try{const result=await window.maintainerApi.publishRelease({...release});release.token="";status.value=`GitHub 发布完成：${result.published.join("、")}`}catch(error){status.value=String(error)}finally{busy.value=false}}
onMounted(()=>load());
</script>
<template><div class="maintainer"><aside><header><span>M</span><div><h1>资料维护器</h1><p>表单维护 · 校验 · 发布</p></div></header><button class="directory" @click="choose">选择资料目录</button><small>{{ data?.directory }}</small><nav><button v-for="item in datasetLabels" :key="item.id" :class="{active:dataset===item.id}" @click="dataset=item.id;selected=null">{{ item.name }}<b>{{ data?.counts?.[item.id]??0 }}</b></button></nav><div class="version"><label>资料版本<input v-model="contentVersion" placeholder="2026.07.17.1"></label></div></aside><main><header class="toolbar"><div><span>本地公共资料</span><h2>{{ datasetLabels.find(item=>item.id===dataset)?.name }}</h2></div><input v-model="query" type="search" placeholder="搜索当前资料…"><button @click="add">＋ 新增</button></header><p :class="['status',{error:status.startsWith('Error')||status.includes('失败')||status.includes('无效')}]">{{ busy?'正在处理…':status }}</p><section class="content"><div class="record-list"><button v-for="item in records" :key="item.id??item.itemId" :class="{active:(selected?.id??selected?.itemId)===(item.id??item.itemId)}" @click="select(item)"><strong>{{ label(item) }}</strong><small>{{ sublabel(item) }}</small></button><p v-if="!records.length">没有匹配资料</p></div><form v-if="selected" class="editor" @submit.prevent="save"><header><div><span>{{ selected.id??selected.itemId??'新资料' }}</span><h3>{{ label(selected)||'新增资料' }}</h3></div><button type="button" @click="selected=null">×</button></header>
<template v-if="dataset==='market'"><label>名称<input v-model="selected.name" required></label><div class="form-row"><label>分类<select v-model.number="selected.legacyType"><option v-for="(name,index) in ['木','石','麻','兽','特殊材料','半成品','护甲','护盾','帽子','刀','弓箭','霰弹枪','冲锋枪','突击步枪','狙击枪','榴弹炮','喷火器','手枪','盾牌','电磁机枪','无人机','消耗品']" :value="index">{{ name }}</option></select></label><label>等级<input v-model.number="selected.level" type="number" min="0"></label><label>采集券<input v-model.number="selected.couponCost" type="number" min="0"></label></div><label>配方材料<textarea v-model="selected.recipeText" rows="9" placeholder="每行一项：材料名称 | 数量 | 制作或购买&#10;例如：木头 | 10 | 制作"></textarea><small>材料名称必须已存在；保存时自动转换为稳定 ID。</small></label></template>
<template v-else-if="dataset==='nano'"><label>物品<select v-model="selected.itemId" :disabled="nanoExists(selected.itemId)"><option v-for="item in data.marketOptions" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><div v-for="key in ['nano1','nano2','nano3']" :key="key" class="nano-row"><strong>{{ key.toUpperCase() }}</strong><label>最小<input v-model.number="selected[key].min" type="number" min="0" step="any"></label><label>平均<input v-model.number="selected[key].average" type="number" min="0" step="any"></label><label>最大<input v-model.number="selected[key].max" type="number" min="0" step="any"></label></div></template>
<template v-else-if="dataset==='cookbook'"><label>食谱名<input v-model="selected.name" required></label><label>获得方法<textarea v-model="selected.method" rows="3"></textarea></label><label>食用效果<textarea v-model="selected.effect" rows="6"></textarea></label><label>持续时间<input v-model="selected.duration"></label><label class="checkbox"><input v-model="selected.defaultUnlocked" type="checkbox">默认已解锁</label></template>
<template v-else-if="dataset==='activities'"><label>分类<select v-model="selected.category"><option v-for="item in data.activityCategories" :value="item.id">{{ item.name }}</option></select></label><label>标题<input v-model="selected.title" required></label><div class="form-row"><label>期数 / 版本<input v-model="selected.version"></label><label>层数<input v-model.number="selected.floors" type="number" min="0"></label></div><div class="form-row"><label>开始日期<input v-model="selected.startDate" type="date" required></label><label>结束日期<input v-model="selected.endDate" type="date"></label></div><label>备注<textarea v-model="selected.condition" rows="5"></textarea></label></template>
<template v-else><label class="checkbox"><input v-model="newsEnabled" type="checkbox">启用客户端快报发布通道</label><label>标题<input v-model="selected.title" required></label><label>发布日期<input v-model="selected.publishedDate" type="date" required></label><div class="image-picker"><button type="button" @click="chooseNewsImage">选择电脑上的长图</button><span>{{ selected.imageFile || '尚未选择本地长图' }}</span></div><label>或者使用现有 HTTPS 图片地址<input v-model="selected.imageUrl" type="url" :disabled="Boolean(selected.imageFile)" placeholder="本地选图后无需填写"><small>推荐直接选择本地图片；发布时会自动上传到 GitHub。</small></label></template>
<footer><button v-if="selected.id||selected.itemId" type="button" class="danger" @click="remove">删除</button><span></span><button type="button" class="secondary" @click="selected=null">取消</button><button type="submit">校验并保存</button></footer></form></section><details class="release"><summary>生成 / 发布 GitHub 资料更新</summary><div class="release-grid"><label>仓库<input v-model="release.repository"></label><label>分支<input v-model="release.branch"></label><label>资料版本<input v-model="release.contentVersion"></label><label>最新客户端版本<input v-model="release.latestVersion"></label><label>最低可用客户端<input v-model="release.minimumSupportedVersion"></label><label>更新级别<select v-model="release.updateLevel"><option value="optional">可选</option><option value="recommended">建议</option><option value="required">必须</option></select></label><label>宽限天数<input v-model.number="release.graceDays" type="number" min="0" max="90"></label><label class="checkbox"><input v-model="release.includeNews" type="checkbox">发布快报（会联网校验所有长图）</label><label class="wide">更新说明<textarea v-model="release.updateMessage" rows="3"></textarea></label><label class="wide">GitHub Token（仅保存在本次输入中）<input v-model="release.token" type="password" autocomplete="off"></label></div><div class="release-actions"><button class="secondary" @click="build">生成到本地</button><button @click="publish">直接发布到 GitHub</button></div></details></main></div></template>
