<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";
import { withAutomaticNews } from "./release-policy";
type Dataset = "market"|"nano"|"cookbook"|"activities"|"news";
const data=ref<any>(null),dataset=ref<Dataset>("market"),query=ref(""),selected=ref<any>(null),status=ref(""),busy=ref(false),listExpanded=ref(false),activeActivityCategory=ref(""),releasePanel=ref<HTMLDetailsElement|null>(null),contentVersion=ref("2026.07.17.1"),newsEnabled=ref(false);
const release=reactive({repository:"chincika/lifeafter-growth-assistant",branch:"main",contentVersion:"2026.07.17.1",latestVersion:"0.1.5",minimumClientVersion:"0.1.0",minimumSupportedVersion:"0.1.0",updateLevel:"optional",updateMessage:"公共资料更新",graceDays:7,token:""});
const datasetLabels:{id:Dataset;name:string}[]=[{id:"market",name:"物品与配方"},{id:"nano",name:"纳米"},{id:"cookbook",name:"食谱"},{id:"activities",name:"活动"},{id:"news",name:"幸存者快报"}];
const activityCategories=computed(()=>[...(data.value?.activityCategories??[])].sort((a:any,b:any)=>a.sortOrder-b.sortOrder));
const currentActivityCategory=computed(()=>activityCategories.value.find((item:any)=>item.id===activeActivityCategory.value));
const records=computed(()=>{const values=dataset.value==="market"?data.value?.marketItems:dataset.value==="nano"?data.value?.nanoItems:dataset.value==="cookbook"?data.value?.cookbookRecipes:dataset.value==="activities"?data.value?.activities:data.value?.newsEntries;const keyword=query.value.trim().toLowerCase();const scoped=dataset.value==="activities"?(values??[]).filter((item:any)=>item.category===activeActivityCategory.value):(values??[]);const filtered=scoped.filter((item:any)=>!keyword||`${item.name??item.title??""} ${item.method??item.version??""} ${item.condition??""}`.toLowerCase().includes(keyword));return dataset.value==="activities"?[...filtered].sort((a:any,b:any)=>String(b.startDate??"").localeCompare(String(a.startDate??""))):filtered;});
function label(item:any){return item.name??item.title??item.itemId??item.id}function sublabel(item:any){return dataset.value==="market"?`${item.categoryName} · Lv ${item.level}`:dataset.value==="nano"?`I ${item.nano1.average} · II ${item.nano2.average} · III ${item.nano3.average}`:dataset.value==="cookbook"?item.method:dataset.value==="activities"?`${item.startDate}${item.endDate?` → ${item.endDate}`:""}${item.condition?` · ${item.condition}`:""}`:item.publishedDate;}
function nanoExists(id:string){return records.value.some((item:any)=>item.itemId===id)}
async function load(directory?:string){busy.value=true;try{data.value=await window.maintainerApi.load(directory);contentVersion.value=data.value.suggestedContentVersion;release.contentVersion=data.value.suggestedContentVersion;newsEnabled.value=data.value.newsEnabled;release.token=await window.maintainerApi.getStoredToken();if(!data.value.activityCategories.some((item:any)=>item.id===activeActivityCategory.value))activeActivityCategory.value=data.value.activityCategories[0]?.id??"";selected.value=null;listExpanded.value=false;status.value=`资料校验通过；下次发布版本 ${data.value.suggestedContentVersion}`}catch(error){status.value=String(error)}finally{busy.value=false}}
async function choose(){const directory=await window.maintainerApi.chooseDirectory();if(directory)await load(directory)}
function switchDataset(value:Dataset){dataset.value=value;selected.value=null;listExpanded.value=false;query.value=""}
function select(item:any){selected.value=JSON.parse(JSON.stringify(item));if(dataset.value==="activities")activeActivityCategory.value=item.category;listExpanded.value=false}
function closeEditor(){selected.value=null;listExpanded.value=true}
function add(){if(dataset.value==="market")selected.value={name:"",legacyType:5,level:1,couponCost:0,recipeText:""};else if(dataset.value==="nano")selected.value={itemId:data.value.marketOptions[0]?.id,nano1:{min:0,average:0,max:0},nano2:{min:0,average:0,max:0},nano3:{min:0,average:0,max:0}};else if(dataset.value==="cookbook")selected.value={name:"",method:"",effect:"",duration:"",defaultUnlocked:false};else if(dataset.value==="activities")selected.value={category:activeActivityCategory.value,title:"",version:"",condition:"",floors:null,startDate:new Date().toLocaleDateString("sv-SE"),endDate:""};else selected.value={title:"",publishedDate:new Date().toLocaleDateString("sv-SE"),imageUrl:"",imageFile:""};listExpanded.value=false}
async function chooseNewsImage(){if(!selected.value)return;const image=await window.maintainerApi.chooseNewsImage();if(!image)return;selected.value.imageFile=image.imageFile;selected.value.imageUrl="";status.value=`已选择长图：${image.width}×${image.height} · ${(image.sizeBytes/1024/1024).toFixed(1)} MiB`;}
async function save(){if(!selected.value)return;busy.value=true;try{const record=JSON.parse(JSON.stringify(selected.value));data.value=await window.maintainerApi.saveRecord({dataset:dataset.value,record,contentVersion:contentVersion.value,newsEnabled:newsEnabled.value});selected.value=null;release.contentVersion=contentVersion.value;status.value="已校验并保存；原文件旁已生成 .bak 保护副本"}catch(error){status.value=String(error)}finally{busy.value=false}}
async function remove(){if(!selected.value?.id&&!selected.value?.itemId)return;if(!confirm(`确定删除“${label(selected.value)}”？`))return;busy.value=true;try{data.value=await window.maintainerApi.deleteRecord({dataset:dataset.value,id:selected.value.id??selected.value.itemId});selected.value=null;status.value="已删除并重新校验资料"}catch(error){status.value=String(error)}finally{busy.value=false}}
function fullReleaseInput(){return withAutomaticNews(release,newsEnabled.value)}
async function build(){busy.value=true;try{const result=await window.maintainerApi.buildRelease(fullReleaseInput());if(!result.canceled)status.value=`发布包已生成：${result.directory}`}catch(error){status.value=String(error)}finally{busy.value=false}}
async function runPublish(input:any,label:string){busy.value=true;try{const result=await window.maintainerApi.publishRelease(input);contentVersion.value=result.contentVersion;release.contentVersion=result.contentVersion;status.value=result.tokenSaved?`${label}发布完成（资料版本 ${result.contentVersion}）；Token 已由 Windows 加密记住`:`${label}发布完成（资料版本 ${result.contentVersion}），但 Token 保存失败：${result.tokenSaveWarning}`}catch(error){status.value=String(error)}finally{busy.value=false}}
async function publish(){if(!confirm(`将直接写入 GitHub 仓库 ${release.repository} 的 ${release.branch} 分支，并自动发布当前快报资料，确定继续？`))return;await runPublish(fullReleaseInput(),"GitHub 资料")}
async function publishActivityCategory(){if(selected.value){status.value="请先保存或取消当前编辑，再发布这个活动分类";return}const category=currentActivityCategory.value;if(!category)return;if(!release.token){if(releasePanel.value){releasePanel.value.open=true;releasePanel.value.scrollIntoView({behavior:"smooth",block:"start"})}status.value="请先在底部填写一次 GitHub Token；成功发布后会自动记住";return}if(!confirm(`发布“${category.name}”的活动时间与更新内容？`))return;release.updateMessage=`${category.name}活动更新`;await runPublish({...release,includeNews:false,updateMessage:release.updateMessage},`“${category.name}”活动`)}
async function clearToken(){if(!confirm("清除这台电脑上保存的 GitHub Token？"))return;await window.maintainerApi.clearStoredToken();release.token="";status.value="已清除保存的 GitHub Token"}
onMounted(()=>load());
</script>
<template><div class="maintainer"><aside><header><span>M</span><div><h1>资料维护器</h1><p>表单维护 · 校验 · 发布</p></div></header><button class="directory" @click="choose">选择资料目录</button><small>{{ data?.directory }}</small><nav><button v-for="item in datasetLabels" :key="item.id" :class="{active:dataset===item.id}" @click="switchDataset(item.id)">{{ item.name }}<b>{{ data?.counts?.[item.id]??0 }}</b></button></nav><div class="version"><label>下次资料版本<input v-model="contentVersion" placeholder="2026.07.17.1"></label><small>发布时会与 GitHub 核对；重复版本会自动递增。</small></div></aside><main><header class="toolbar"><div><span>本地公共资料</span><h2>{{ datasetLabels.find(item=>item.id===dataset)?.name }}</h2></div><input v-model="query" type="search" :placeholder="dataset==='activities'?'搜索当前活动分类…':'搜索当前资料…'"><button @click="add">＋ 新增</button></header><p :class="['status',{error:status.startsWith('Error')||status.includes('失败')||status.includes('无效')}]">{{ busy?'正在处理…':status }}</p><section v-if="dataset==='activities'" class="activity-category-panel"><nav class="activity-category-tabs" aria-label="活动分类"><button v-for="item in activityCategories" :key="item.id" type="button" :class="{active:activeActivityCategory===item.id}" @click="activeActivityCategory=item.id;selected=null;listExpanded=false;query=''">{{ item.name }}<small>{{ data.activities.filter((entry:any)=>entry.category===item.id).length }}</small></button></nav><div class="activity-category-context"><div><span>当前独立维护</span><strong>{{ currentActivityCategory?.name }}</strong><small>使用生效时间、结束时间和文字内容独立更新；只有幸存者快报使用长图。</small></div><button type="button" :disabled="busy" @click="publishActivityCategory">发布本分类更新</button></div></section><section class="content" :class="{editing:Boolean(selected)}"><section v-if="!selected" class="record-browser"><button type="button" class="record-browser-toggle" :aria-expanded="listExpanded" @click="listExpanded=!listExpanded"><span><b>{{ records.length }}</b> 条{{ dataset==='activities'?currentActivityCategory?.name:datasetLabels.find(item=>item.id===dataset)?.name }}资料</span><small>{{ listExpanded?'收起资料列表':'展开查看、编辑或删除资料' }}</small><i>{{ listExpanded?'⌃':'⌄' }}</i></button><div v-if="listExpanded" class="record-list"><button v-for="item in records" :key="item.id??item.itemId" @click="select(item)"><strong>{{ label(item) }}</strong><small>{{ sublabel(item) }}</small></button><p v-if="!records.length">没有匹配资料</p></div></section><form v-if="selected" class="editor" @submit.prevent="save"><header><div><span>{{ selected.id??selected.itemId??'新资料' }}</span><h3>{{ label(selected)||'新增资料' }}</h3></div><button type="button" class="editor-back" @click="closeEditor">← 返回列表</button></header>
<template v-if="dataset==='market'"><label>名称<input v-model="selected.name" required></label><div class="form-row"><label>分类<select v-model.number="selected.legacyType"><option v-for="(name,index) in ['木','石','麻','兽','特殊材料','半成品','护甲','护盾','帽子','刀','弓箭','霰弹枪','冲锋枪','突击步枪','狙击枪','榴弹炮','喷火器','手枪','盾牌','电磁机枪','无人机','消耗品']" :value="index">{{ name }}</option></select></label><label>等级<input v-model.number="selected.level" type="number" min="0"></label><label>采集券<input v-model.number="selected.couponCost" type="number" min="0"></label></div><label>配方材料<textarea v-model="selected.recipeText" rows="9" placeholder="每行一项：材料名称 | 数量 | 制作或购买&#10;例如：木头 | 10 | 制作"></textarea><small>材料名称必须已存在；保存时自动转换为稳定 ID。</small></label></template>
<template v-else-if="dataset==='nano'"><label>物品<select v-model="selected.itemId" :disabled="nanoExists(selected.itemId)"><option v-for="item in data.marketOptions" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><div v-for="key in ['nano1','nano2','nano3']" :key="key" class="nano-row"><strong>{{ key.toUpperCase() }}</strong><label>最小<input v-model.number="selected[key].min" type="number" min="0" step="any"></label><label>平均<input v-model.number="selected[key].average" type="number" min="0" step="any"></label><label>最大<input v-model.number="selected[key].max" type="number" min="0" step="any"></label></div></template>
<template v-else-if="dataset==='cookbook'"><label>食谱名<input v-model="selected.name" required></label><label>获得方法<textarea v-model="selected.method" rows="3"></textarea></label><label>食用效果<textarea v-model="selected.effect" rows="6"></textarea></label><label>持续时间<input v-model="selected.duration"></label><label class="checkbox"><input v-model="selected.defaultUnlocked" type="checkbox">默认已解锁</label></template>
<template v-else-if="dataset==='activities'"><div class="activity-edit-context"><span>正在维护</span><strong>{{ currentActivityCategory?.name }}</strong><small>保存后只会更新这个分类中的记录。</small></div><label>活动标题<input v-model="selected.title" required></label><div class="form-row"><label>期数 / 版本<input v-model="selected.version" placeholder="例如：第 201 期或 S27"></label><label>层数（没有可不填）<input v-model.number="selected.floors" type="number" min="0"></label></div><div class="form-row"><label>开始 / 生效日期<input v-model="selected.startDate" type="date" required></label><label>结束日期<input v-model="selected.endDate" type="date"></label></div><label>更新内容（会显示在客户端）<textarea v-model="selected.condition" rows="6" maxlength="2000" placeholder="填写本次活动内容、折扣范围、参与条件等"></textarea><small>此处内容随本分类时间一起热更新。</small></label></template>
<template v-else><label class="checkbox"><input v-model="newsEnabled" type="checkbox">启用客户端快报发布通道</label><label>标题<input v-model="selected.title" required></label><label>发布日期<input v-model="selected.publishedDate" type="date" required></label><div class="image-picker"><button type="button" @click="chooseNewsImage">选择电脑上的长图</button><span>{{ selected.imageFile || '尚未选择本地长图' }}</span></div><label>或者使用现有 HTTPS 图片地址<input v-model="selected.imageUrl" type="url" :disabled="Boolean(selected.imageFile)" placeholder="本地选图后无需填写"><small>推荐直接选择本地图片；发布时会自动上传到 GitHub。</small></label></template>
<footer><button v-if="selected.id||selected.itemId" type="button" class="danger" @click="remove">删除</button><span></span><button type="button" class="secondary" @click="closeEditor">取消</button><button type="submit">校验并保存</button></footer></form></section><details ref="releasePanel" class="release"><summary>生成 / 发布 GitHub 资料更新</summary><div class="release-grid"><label>仓库<input v-model="release.repository"></label><label>分支<input v-model="release.branch"></label><label>资料版本<input v-model="release.contentVersion"></label><label>最新客户端版本<input v-model="release.latestVersion"></label><label>最低可用客户端<input v-model="release.minimumSupportedVersion"></label><label>更新级别<select v-model="release.updateLevel"><option value="optional">可选</option><option value="recommended">建议</option><option value="required">必须</option></select></label><label>宽限天数<input v-model.number="release.graceDays" type="number" min="0" max="90"></label><div class="release-policy"><strong>快报自动随通用发布更新</strong><small>点击“直接发布到 GitHub”时会自动上传并校验当前快报长图；单独发布活动分类不会改动快报。</small></div><label class="wide">更新说明<textarea v-model="release.updateMessage" rows="3"></textarea></label><label class="wide">GitHub Token（Windows 当前账户加密保存）<input v-model="release.token" type="password" autocomplete="off"><small>成功发布后自动记住；不会写入资料目录、发布包或 GitHub。</small></label></div><div class="release-actions"><button v-if="release.token" class="secondary" @click="clearToken">清除已保存 Token</button><span></span><button class="secondary" @click="build">生成到本地</button><button @click="publish">直接发布到 GitHub</button></div></details></main></div></template>
